"""
Scholarly etymology sources catalog.

ALL_SOURCES: every source as a dict ready for Neo4j ingestion via LexiconIngestor.ingest_source()
LEGACY_SOURCE_MAP: free-text strings used in the original seed_data.py → canonical slugs

Authority tiers:
  1 = primary etymological dictionaries (de Vaan, Beekes, Barnhart, Watkins...)
  2 = major historical dictionaries (OED, Century Dictionary, Webster 1828...)
  3 = specialist references & primary texts (KJV, Shakespeare, Chaucer, Niermeyer...)
  4 = slang, dialect, and usage guides (Partridge, Grose, Fowler, Mencken...)
"""

ALL_SOURCES = [

    # ── Tier 1: Primary Etymological ─────────────────────────────────────────

    {
        "slug": "barnhart-1988",
        "short_name": "Barnhart 1988",
        "full_name": "The Barnhart Dictionary of Etymology",
        "author": "Robert K. Barnhart",
        "year": 1988,
        "publisher": "H.W. Wilson",
        "category": "etymological",
        "authority_tier": 1,
        "description": "The standard one-volume English etymology reference; concise, reliable, widely cited.",
    },
    {
        "slug": "beekes-2010",
        "short_name": "Beekes 2010",
        "full_name": "Etymological Dictionary of Greek",
        "author": "Robert Beekes",
        "year": 2010,
        "publisher": "Brill",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Definitive modern reference for Ancient Greek etymologies, including pre-Greek substrate analysis.",
    },
    {
        "slug": "de-vaan-2008",
        "short_name": "de Vaan 2008",
        "full_name": "Etymological Dictionary of Latin and the other Italic Languages",
        "author": "Michiel de Vaan",
        "year": 2008,
        "publisher": "Brill",
        "category": "etymological",
        "authority_tier": 1,
        "description": "The current standard for Latin etymologies; traces roots back to PIE with full cognate sets.",
    },
    {
        "slug": "watkins-pie-2000",
        "short_name": "Watkins PIE 2000",
        "full_name": "The American Heritage Dictionary of Indo-European Roots",
        "author": "Calvert Watkins",
        "year": 2000,
        "publisher": "Houghton Mifflin",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Indispensable guide to PIE roots underlying English vocabulary; appendix to the American Heritage Dictionary.",
    },
    {
        "slug": "klein-1971",
        "short_name": "Klein 1971",
        "full_name": "A Comprehensive Etymological Dictionary of the English Language",
        "author": "Ernest Klein",
        "year": 1971,
        "publisher": "Elsevier",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Exhaustive two-volume work covering 44,000+ English words with full Latin, Greek, and Hebrew roots.",
    },
    {
        "slug": "liberman-2008",
        "short_name": "Liberman 2008",
        "full_name": "An Analytic Dictionary of English Etymology",
        "author": "Anatoly Liberman",
        "year": 2008,
        "publisher": "University of Minnesota Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Critical survey of existing etymologies with extensive bibliographic commentary; corrects many received accounts.",
    },
    {
        "slug": "pokorny-1959",
        "short_name": "Pokorny 1959",
        "full_name": "Indogermanisches etymologisches Wörterbuch",
        "author": "Julius Pokorny",
        "year": 1959,
        "publisher": "Francke",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Foundational two-volume PIE root dictionary; still cited for its comprehensive cognate documentation despite some outdated reconstructions.",
    },
    {
        "slug": "lewis-short",
        "short_name": "Lewis & Short",
        "full_name": "A Latin Dictionary",
        "author": "Charlton T. Lewis and Charles Short",
        "year": 1879,
        "publisher": "Clarendon Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "The standard Latin-English reference dictionary; documents word meanings with quotations from classical through late Latin.",
    },
    {
        "slug": "liddell-scott",
        "short_name": "Liddell-Scott",
        "full_name": "A Greek-English Lexicon",
        "author": "Henry G. Liddell and Robert Scott",
        "year": 1940,
        "publisher": "Clarendon Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "The definitive Ancient Greek dictionary; the 9th edition (1940) remains the scholarly standard.",
    },
    {
        "slug": "hall-1894",
        "short_name": "Hall 1894",
        "full_name": "A Concise Anglo-Saxon Dictionary",
        "author": "John R. Clark Hall",
        "year": 1894,
        "publisher": "Cambridge University Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Standard compact reference for Old English vocabulary; essential for tracing pre-Norman word histories.",
    },
    {
        "slug": "mec-corpus",
        "short_name": "Middle English Compendium",
        "full_name": "Middle English Compendium / Middle English Dictionary",
        "author": "Frances McSparran et al.",
        "year": 2000,
        "publisher": "University of Michigan",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Comprehensive dictionary and corpus of Middle English (1100–1500); documents word meanings from Chaucer through the late medieval period.",
    },
    {
        "slug": "zoega-icelandic",
        "short_name": "Zoëga 1910",
        "full_name": "A Concise Dictionary of Old Icelandic",
        "author": "Geir T. Zoëga",
        "year": 1910,
        "publisher": "Clarendon Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Standard reference for Old Norse vocabulary; essential for tracing Scandinavian loans into English.",
    },
    {
        "slug": "skeat-1882",
        "short_name": "Skeat 1882",
        "full_name": "An Etymological Dictionary of the English Language",
        "author": "Walter W. Skeat",
        "year": 1882,
        "publisher": "Clarendon Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Victorian-era foundational English etymology dictionary; extensive and broadly reliable despite its age.",
    },
    {
        "slug": "bosworth-toller",
        "short_name": "Bosworth-Toller",
        "full_name": "An Anglo-Saxon Dictionary",
        "author": "Joseph Bosworth and T. Northcote Toller",
        "year": 1898,
        "publisher": "Clarendon Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "The comprehensive Old English dictionary; documents all attested Old English vocabulary with quotations from manuscript sources.",
    },
    {
        "slug": "mayrhofer-ewaia",
        "short_name": "Mayrhofer EWAia",
        "full_name": "Etymologisches Wörterbuch des Altindoarischen",
        "author": "Manfred Mayrhofer",
        "year": 1992,
        "publisher": "Heidelberg",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Definitive Sanskrit etymological dictionary; essential for establishing PIE roots shared with English.",
    },
    {
        "slug": "kluge-1899",
        "short_name": "Kluge 1899",
        "full_name": "Etymologisches Wörterbuch der deutschen Sprache",
        "author": "Friedrich Kluge",
        "year": 1899,
        "publisher": "Trübner",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Standard German etymological dictionary; invaluable for tracing Germanic roots shared with English.",
    },
    {
        "slug": "matasovic-2009",
        "short_name": "Matasović 2009",
        "full_name": "Etymological Dictionary of Proto-Celtic",
        "author": "Ranko Matasović",
        "year": 2009,
        "publisher": "Brill",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Authoritative dictionary of Proto-Celtic reconstructions; covers Celtic loans into English via Gaulish and Brythonic.",
    },

    # ── Tier 2: Major Historical Dictionaries ─────────────────────────────────

    {
        "slug": "oed-2e",
        "short_name": "OED 2nd ed.",
        "full_name": "Oxford English Dictionary, Second Edition",
        "author": "John Simpson and Edmund Weiner",
        "year": 1989,
        "publisher": "Oxford University Press",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "The largest historical dictionary of the English language; documents every word's first attested use with quotations from 1150 to the present.",
    },
    {
        "slug": "dotish-philosopher",
        "short_name": "DotishPhilosopher",
        "full_name": "DotishPhilosopher Lexicon",
        "author": "DotishPhilosopher",
        "year": 2026,
        "publisher": "DotishPhilosopher",
        "category": "online-lexicon",
        "authority_tier": 3,
        "description": "Imported lexicon data from DotishPhilosopher.",
    },
    {
        "slug": "etymology-seed-database",
        "short_name": "Etymology Seed Database",
        "full_name": "Etymology Seed Database",
        "author": "Living Lexicon Project",
        "year": 2026,
        "publisher": "Living Lexicon Project",
        "category": "seed-data",
        "authority_tier": 3,
        "description": "Foundational etymological seed data with historical contexts.",
    },
    {
        "slug": "etymwordnet",
        "short_name": "EtymWordNet",
        "full_name": "EtymWordNet",
        "author": "Gerard de Melo",
        "year": 2014,
        "publisher": "Max Planck Institute for Informatics",
        "category": "lexical-database",
        "authority_tier": 3,
        "description": "Machine-readable etymological relationships used as a broad-coverage backbone before scholarly enrichment.",
    },
    {
        "slug": "princeton-wordnet",
        "short_name": "Princeton WordNet",
        "full_name": "WordNet: A Lexical Database for English",
        "author": "Christiane Fellbaum et al.",
        "year": 1998,
        "publisher": "Princeton University",
        "category": "lexical-database",
        "authority_tier": 3,
        "description": "Broad English lexical database used for headword coverage and modern lexical senses.",
    },
    {
        "slug": "open-english-wordnet",
        "short_name": "Open English WordNet",
        "full_name": "Open English WordNet",
        "author": "John P. McCrae, Alexandre Rademaker, Francis Bond, Ewa Rudnicka, Christiane Fellbaum et al.",
        "year": 2024,
        "publisher": "Global WordNet Association / Oxford Text Archive",
        "category": "lexical-database",
        "authority_tier": 3,
        "description": "Open-source English WordNet release with synsets, definitions, and lexical-semantic relations.",
    },
    {
        "slug": "wikidata-lexemes",
        "short_name": "Wikidata Lexemes",
        "full_name": "Wikidata Lexicographical Data",
        "author": "Wikidata contributors",
        "year": 2026,
        "publisher": "Wikimedia Foundation",
        "category": "lexical-database",
        "authority_tier": 3,
        "description": "CC0 structured lexeme identifiers, lemmas, forms, senses, and language metadata from Wikidata.",
    },
    {
        "slug": "kaikki-wiktextract",
        "short_name": "Kaikki/Wiktextract",
        "full_name": "Kaikki.org machine-readable Wiktionary extracted with Wiktextract",
        "author": "Tatu Ylonen and Wiktionary contributors",
        "year": 2026,
        "publisher": "Kaikki.org / Wikimedia",
        "category": "lexical-database",
        "authority_tier": 3,
        "description": "Structured Wiktionary-derived lexical data for definitions, etymologies, forms, translations, and related terms.",
    },
    {
        "slug": "etymology-db",
        "short_name": "Etymology DB",
        "full_name": "Etymology DB",
        "author": "droher",
        "year": 2023,
        "publisher": "GitHub",
        "category": "lexical-database",
        "authority_tier": 3,
        "description": "Open structured multilingual etymology dataset generated from Wiktionary data.",
    },
    {
        "slug": "gcide",
        "short_name": "GCIDE",
        "full_name": "GNU Collaborative International Dictionary of English",
        "author": "Patrick J. Cassidy et al.",
        "year": 2026,
        "publisher": "GNU",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "Free English dictionary derived from Webster 1913 and supplemented with WordNet and volunteer edits.",
    },
    {
        "slug": "wordfreq",
        "short_name": "wordfreq",
        "full_name": "wordfreq",
        "author": "Robyn Speer et al.",
        "year": 2023,
        "publisher": "Luminoso / Python Package Index",
        "category": "frequency",
        "authority_tier": 4,
        "description": "Open word-frequency estimates used to prioritize enrichment and rank common vocabulary.",
    },
    {
        "slug": "subtlex-us",
        "short_name": "SUBTLEX-US",
        "full_name": "SUBTLEX-US Word Frequency Database",
        "author": "Marc Brysbaert and Boris New",
        "year": 2009,
        "publisher": "Behavior Research Methods",
        "category": "frequency",
        "authority_tier": 4,
        "description": "American English subtitle frequency data for prioritizing high-use modern vocabulary.",
    },
    {
        "slug": "scowl",
        "short_name": "SCOWL",
        "full_name": "Spell Checker Oriented Word Lists",
        "author": "Kevin Atkinson et al.",
        "year": 2025,
        "publisher": "SCOWL and Friends",
        "category": "word-list",
        "authority_tier": 4,
        "description": "Spellchecker-oriented English word lists used for validation, dialect variants, and headword filtering.",
    },
    {
        "slug": "moby-word-lists",
        "short_name": "Moby Word Lists",
        "full_name": "Moby Word Lists",
        "author": "Grady Ward",
        "year": 2001,
        "publisher": "Project Gutenberg",
        "category": "word-list",
        "authority_tier": 4,
        "description": "Public-domain English word lists used for coverage checks and candidate headword validation.",
    },
    {
        "slug": "century-dictionary",
        "short_name": "Century Dictionary",
        "full_name": "The Century Dictionary and Cyclopedia",
        "author": "William Dwight Whitney",
        "year": 1889,
        "publisher": "The Century Co.",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "The largest American dictionary ever produced; rich in 19th-century scientific and technical vocabulary.",
    },
    {
        "slug": "webster-1828",
        "short_name": "Webster 1828",
        "full_name": "An American Dictionary of the English Language",
        "author": "Noah Webster",
        "year": 1828,
        "publisher": "S. Converse",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "First major American dictionary; captures Early Modern meanings that OED tracks from British sources, with American contextual notes.",
    },
    {
        "slug": "dare",
        "short_name": "DARE",
        "full_name": "Dictionary of American Regional English",
        "author": "Frederic G. Cassidy",
        "year": 1985,
        "publisher": "Belknap Press",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "Documents American regional dialects; essential for tracing how standard meanings diverged across American English varieties.",
    },
    {
        "slug": "ned-1884",
        "short_name": "NED 1884",
        "full_name": "A New English Dictionary on Historical Principles",
        "author": "James Murray",
        "year": 1884,
        "publisher": "Clarendon Press",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "The original fascicle-published form of the OED; some early volumes contain denser etymological notes than the revised edition.",
    },
    {
        "slug": "johnson-1755",
        "short_name": "Johnson 1755",
        "full_name": "A Dictionary of the English Language",
        "author": "Samuel Johnson",
        "year": 1755,
        "publisher": "W. Strahan",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "First systematic English dictionary; captures 18th-century semantic states at the transition from Early Modern usage.",
    },

    # ── Tier 3: Specialist References & Primary Texts ─────────────────────────

    {
        "slug": "kjv-1611",
        "short_name": "KJV 1611",
        "full_name": "The Holy Bible, King James Version",
        "author": "KJV Translation Committee",
        "year": 1611,
        "publisher": "Robert Barker, Royal Printer",
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The King James Bible; the single most important document for understanding Early Modern English word usage and the source of most 'false-friend' misreadings.",
    },
    {
        "slug": "shakespeare",
        "short_name": "Shakespeare",
        "full_name": "The Complete Works of William Shakespeare",
        "author": "William Shakespeare",
        "year": 1623,
        "publisher": "First Folio",
        "category": "primary-text",
        "authority_tier": 3,
        "description": "Shakespeare's works (c.1590–1613) document the full range of Early Modern English register — from legal to slang — at peak expressiveness.",
    },
    {
        "slug": "wycliffe-1382",
        "short_name": "Wycliffe 1382",
        "full_name": "Wycliffe Bible",
        "author": "John Wycliffe",
        "year": 1382,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "First complete English Bible translation; documents Late Middle English word forms and meanings during the religious vocabulary transition.",
    },
    {
        "slug": "tyndale-1526",
        "short_name": "Tyndale 1526",
        "full_name": "The Tyndale Bible (New Testament)",
        "author": "William Tyndale",
        "year": 1526,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The most influential English Bible before KJV; Tyndale's word choices were adopted wholesale by KJV translators.",
    },
    {
        "slug": "vulgate-latin",
        "short_name": "Vulgate Latin",
        "full_name": "Biblia Sacra Vulgata",
        "author": "Jerome",
        "year": 405,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "Jerome's Latin Bible; the source text for most medieval English translations and the origin of ecclesiastical Latin vocabulary in English.",
    },
    {
        "slug": "niermeyer-1976",
        "short_name": "Niermeyer 1976",
        "full_name": "Mediae Latinitatis Lexicon Minus",
        "author": "J.F. Niermeyer",
        "year": 1976,
        "publisher": "Brill",
        "category": "specialist",
        "authority_tier": 3,
        "description": "Standard dictionary of Medieval Latin (500–1500 AD); documents how classical Latin words shifted meaning in the medieval Church and law.",
    },
    {
        "slug": "chaucer",
        "short_name": "Chaucer",
        "full_name": "The Canterbury Tales and other works",
        "author": "Geoffrey Chaucer",
        "year": 1390,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The central Middle English literary corpus; documents the full French-English vocabulary fusion of the 14th century.",
    },
    {
        "slug": "beowulf",
        "short_name": "Beowulf",
        "full_name": "Beowulf",
        "author": None,
        "year": 900,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The major Old English epic poem; key source for core Germanic vocabulary before the Norman Conquest.",
    },
    {
        "slug": "piers-plowman",
        "short_name": "Piers Plowman",
        "full_name": "Piers Plowman",
        "author": "William Langland",
        "year": 1370,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "Major 14th-century allegorical poem; documents religious and everyday Middle English vocabulary in non-courtly register.",
    },
    {
        "slug": "bcp-1549",
        "short_name": "Book of Common Prayer 1549",
        "full_name": "The Book of Common Prayer",
        "author": "Thomas Cranmer",
        "year": 1549,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The liturgical text of the Church of England; alongside KJV, the most widely memorized Early Modern English prose.",
    },
    {
        "slug": "spenser-faerie-queene",
        "short_name": "Spenser 1590",
        "full_name": "The Faerie Queene",
        "author": "Edmund Spenser",
        "year": 1590,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "Documents deliberate archaism in Early Modern English; Spenser revived Middle English words as a poetic register device.",
    },
    {
        "slug": "milton-1667",
        "short_name": "Milton 1667",
        "full_name": "Paradise Lost",
        "author": "John Milton",
        "year": 1667,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "Late Early Modern English; documents the period when KJV-era word meanings were beginning to shift toward 18th-century usage.",
    },
    {
        "slug": "anglo-saxon-chronicle",
        "short_name": "Anglo-Saxon Chronicle",
        "full_name": "The Anglo-Saxon Chronicle",
        "author": None,
        "year": 900,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The primary prose chronicle of Old English history; essential for documenting everyday Old English vocabulary in non-poetic register.",
    },
    {
        "slug": "geneva-bible-1560",
        "short_name": "Geneva Bible 1560",
        "full_name": "The Geneva Bible",
        "author": None,
        "year": 1560,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The Bible of the Protestant Reformation and Shakespeare's generation; predates KJV and documents an earlier stage of Early Modern English.",
    },
    {
        "slug": "coverdale-1535",
        "short_name": "Coverdale 1535",
        "full_name": "The Coverdale Bible",
        "author": "Miles Coverdale",
        "year": 1535,
        "publisher": None,
        "category": "primary-text",
        "authority_tier": 3,
        "description": "First complete printed English Bible; bridges Tyndale and KJV in the evolution of English biblical vocabulary.",
    },
    {
        "slug": "sweet-1896",
        "short_name": "Sweet 1896",
        "full_name": "The Student's Dictionary of Anglo-Saxon",
        "author": "Henry Sweet",
        "year": 1896,
        "publisher": "Clarendon Press",
        "category": "specialist",
        "authority_tier": 3,
        "description": "Compact Old English reference with etymological notes; useful for tracing Anglo-Saxon words into later English.",
    },
    {
        "slug": "holthausen-ae",
        "short_name": "Holthausen",
        "full_name": "Altenglisches etymologisches Wörterbuch",
        "author": "Ferdinand Holthausen",
        "year": 1934,
        "publisher": "Heidelberg",
        "category": "specialist",
        "authority_tier": 3,
        "description": "Etymological dictionary specifically of Old English; traces Anglo-Saxon words to their Proto-Germanic and PIE sources.",
    },
    {
        "slug": "feist-1939",
        "short_name": "Feist 1939",
        "full_name": "Vergleichendes Wörterbuch der Gotischen Sprache",
        "author": "Sigmund Feist",
        "year": 1939,
        "publisher": "Brill",
        "category": "specialist",
        "authority_tier": 3,
        "description": "The standard Gothic etymological dictionary; Gothic provides the oldest attested Germanic cognates for many English words.",
    },

    # ── Tier 4: Slang, Dialect, and Usage ─────────────────────────────────────

    {
        "slug": "partridge-slang",
        "short_name": "Partridge",
        "full_name": "A Dictionary of Slang and Unconventional English",
        "author": "Eric Partridge",
        "year": 1937,
        "publisher": "George Routledge & Sons",
        "category": "slang",
        "authority_tier": 4,
        "description": "The standard historical dictionary of British English slang; documents non-standard word histories from the 16th century onward.",
    },
    {
        "slug": "grose-1785",
        "short_name": "Grose 1785",
        "full_name": "A Classical Dictionary of the Vulgar Tongue",
        "author": "Francis Grose",
        "year": 1785,
        "publisher": None,
        "category": "slang",
        "authority_tier": 4,
        "description": "18th-century slang dictionary; first attested meanings for dozens of vulgar and street English words.",
    },
    {
        "slug": "farmer-slang",
        "short_name": "Farmer & Henley",
        "full_name": "Slang and Its Analogues Past and Present",
        "author": "John Farmer and William Henley",
        "year": 1890,
        "publisher": None,
        "category": "slang",
        "authority_tier": 4,
        "description": "7-volume historical slang dictionary; the most comprehensive Victorian-era survey of English slang etymology.",
    },
    {
        "slug": "fowler-usage",
        "short_name": "Fowler",
        "full_name": "A Dictionary of Modern English Usage",
        "author": "H.W. Fowler",
        "year": 1926,
        "publisher": "Clarendon Press",
        "category": "slang",
        "authority_tier": 4,
        "description": "The authoritative guide to early 20th-century English usage; documents semantic shifts as they were occurring and prescriptively contested.",
    },
    {
        "slug": "mencken-american",
        "short_name": "Mencken",
        "full_name": "The American Language",
        "author": "H.L. Mencken",
        "year": 1919,
        "publisher": "Alfred A. Knopf",
        "category": "slang",
        "authority_tier": 4,
        "description": "Documents American English divergence from British English; traces Americanisms and borrowings from immigrant languages.",
    },
    {
        "slug": "wentworth-flexner",
        "short_name": "Wentworth-Flexner",
        "full_name": "Dictionary of American Slang",
        "author": "Harold Wentworth and Stuart Berg Flexner",
        "year": 1960,
        "publisher": "Thomas Y. Crowell",
        "category": "slang",
        "authority_tier": 4,
        "description": "Standard mid-20th century American slang dictionary; documents how informal registers entered mainstream usage.",
    },
    {
        "slug": "green-slang-2010",
        "short_name": "Green 2010",
        "full_name": "Green's Dictionary of Slang",
        "author": "Jonathon Green",
        "year": 2010,
        "publisher": "Chambers Harrap",
        "category": "slang",
        "authority_tier": 4,
        "description": "The most comprehensive modern English slang dictionary; traces slang terms from earliest attestation to present usage.",
    },
    {
        "slug": "brewer-1870",
        "short_name": "Brewer 1870",
        "full_name": "Brewer's Dictionary of Phrase and Fable",
        "author": "Ebenezer Cobham Brewer",
        "year": 1870,
        "publisher": None,
        "category": "slang",
        "authority_tier": 4,
        "description": "Victorian reference documenting phrase origins and cultural allusions; useful for tracking figurative semantic shifts.",
    },

    # ── Additional Tier 1 ─────────────────────────────────────────────────────

    {
        "slug": "onions-1966",
        "short_name": "Onions 1966",
        "full_name": "The Oxford Dictionary of English Etymology",
        "author": "C.T. Onions",
        "year": 1966,
        "publisher": "Oxford University Press",
        "category": "etymological",
        "authority_tier": 1,
        "description": "One-volume scholarly English etymology dictionary prepared by the OED's former editor; concise and authoritative.",
    },
    {
        "slug": "weekley-1921",
        "short_name": "Weekley 1921",
        "full_name": "An Etymological Dictionary of Modern English",
        "author": "Ernest Weekley",
        "year": 1921,
        "publisher": "John Murray",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Historically important English etymology dictionary; particularly strong on French and Norman influences.",
    },
    {
        "slug": "du-cange",
        "short_name": "Du Cange",
        "full_name": "Glossarium Mediae et Infimae Latinitatis",
        "author": "Charles du Cange",
        "year": 1678,
        "publisher": None,
        "category": "etymological",
        "authority_tier": 1,
        "description": "The foundational dictionary of Medieval Latin; documents the enormous vocabulary drift of Latin from classical to Church usage.",
    },
    {
        "slug": "godefroy",
        "short_name": "Godefroy",
        "full_name": "Dictionnaire de l'Ancienne Langue Française",
        "author": "Frédéric Godefroy",
        "year": 1881,
        "publisher": None,
        "category": "etymological",
        "authority_tier": 1,
        "description": "Standard dictionary of Old French; critical for tracing the Norman French vocabulary that transformed English after 1066.",
    },
    {
        "slug": "tobler-lommatzsch",
        "short_name": "Tobler-Lommatzsch",
        "full_name": "Altfranzösisches Wörterbuch",
        "author": "Adolf Tobler and Erhard Lommatzsch",
        "year": 1925,
        "publisher": None,
        "category": "etymological",
        "authority_tier": 1,
        "description": "Definitive Old French dictionary; comprehensive coverage of 12th–14th century French vocabulary that entered English.",
    },
    {
        "slug": "cotgrave-1611",
        "short_name": "Cotgrave 1611",
        "full_name": "A Dictionarie of the French and English Tongues",
        "author": "Randle Cotgrave",
        "year": 1611,
        "publisher": None,
        "category": "specialist",
        "authority_tier": 3,
        "description": "Earliest comprehensive French-English dictionary; contemporary with KJV and Shakespeare; documents Early Modern French borrowings.",
    },
    {
        "slug": "and-corpus",
        "short_name": "Anglo-Norman Dictionary",
        "full_name": "Anglo-Norman Dictionary",
        "author": "William Rothwell et al.",
        "year": 2005,
        "publisher": "Aberystwyth University",
        "category": "etymological",
        "authority_tier": 1,
        "description": "Definitive dictionary of Anglo-Norman French as used in England 1066–1400; captures the French that directly entered English.",
    },

    # ── Additional Tier 2 ─────────────────────────────────────────────────────

    {
        "slug": "ahd-4e",
        "short_name": "AHD 4th ed.",
        "full_name": "The American Heritage Dictionary of the English Language, Fourth Edition",
        "author": None,
        "year": 2000,
        "publisher": "Houghton Mifflin",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "Modern desk dictionary with the most thorough PIE root appendix of any general dictionary; excellent for casual etymology lookup.",
    },
    {
        "slug": "mw-collegiate",
        "short_name": "Merriam-Webster",
        "full_name": "Merriam-Webster's Collegiate Dictionary",
        "author": None,
        "year": 2003,
        "publisher": "Merriam-Webster",
        "category": "historical-dictionary",
        "authority_tier": 2,
        "description": "Standard American desk dictionary; concise etymologies trace word histories from first attested use.",
    },

    # ── Additional Tier 3 ─────────────────────────────────────────────────────

    {
        "slug": "dore-1868",
        "short_name": "Doré Bible 1868",
        "full_name": "The Holy Bible with Illustrations by Gustave Doré",
        "author": "Gustave Doré",
        "year": 1868,
        "publisher": "Cassell",
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The standard Victorian illustrated Bible; documents how KJV English was received and glossed in the 19th century.",
    },
    {
        "slug": "authorized-1769",
        "short_name": "KJV Oxford 1769",
        "full_name": "The Holy Bible (Oxford Standard Text, 1769 revision)",
        "author": "Benjamin Blayney",
        "year": 1769,
        "publisher": "Oxford University Press",
        "category": "primary-text",
        "authority_tier": 3,
        "description": "The standardized KJV text still in use today; minor orthographic updates from 1611 original that affect some word form comparisons.",
    },
    {
        "slug": "bp-glossary",
        "short_name": "Book of Prayer Glossary",
        "full_name": "A Glossary of Obsolete and Archaic Words in the Prayer Book and Authorized Version",
        "author": "William Aldis Wright",
        "year": 1884,
        "publisher": "Cambridge University Press",
        "category": "specialist",
        "authority_tier": 3,
        "description": "Victorian scholarly glossary specifically documenting KJV and Book of Common Prayer false-friends; invaluable for word-by-word Early Modern meanings.",
    },
    {
        "slug": "internet-sacred-text-archive",
        "short_name": "Sacred Texts",
        "full_name": "Internet Sacred Text Archive",
        "author": "John B. Hare et al.",
        "year": 2026,
        "publisher": "Internet Sacred Text Archive",
        "category": "primary-text-archive",
        "authority_tier": 3,
        "description": "Religion-agnostic archive of public-domain and freely redistributable sacred, mythological, folklore, and esoteric texts translated into English.",
    },
    {
        "slug": "shipley-1984",
        "short_name": "Shipley 1984",
        "full_name": "The Origins of English Words: A Discursive Dictionary of Indo-European Roots",
        "author": "Joseph T. Shipley",
        "year": 1984,
        "publisher": "Johns Hopkins University Press",
        "category": "etymological",
        "authority_tier": 2,
        "description": "Discursive dictionary of Indo-European roots and English derivatives. Copyrighted source; use for citation-backed root claims and short notes, not bulk text ingestion.",
    },

    # ── Curated project supplements ──────────────────────────────────────────

    {
        "slug": "curated-idioms",
        "short_name": "Curated Idioms",
        "full_name": "Living Lexicon Curated Idiom Supplement",
        "author": "The Living Lexicon project",
        "year": 2026,
        "publisher": "The Living Lexicon",
        "category": "curated-supplement",
        "authority_tier": 4,
        "description": "Project-maintained idiom rows. Treat low-confidence starter rows as placeholders until replaced with dated historical dictionary or primary-text evidence.",
    },
]

# Free-text source strings used in the original seed_data.py → canonical slugs
LEGACY_SOURCE_MAP = {
    "OED":                   "oed-2e",
    "Latin etymology":       "de-vaan-2008",
    "KJV 1611":              "kjv-1611",
    "Shakespeare":           "shakespeare",
    "Middle English corpus": "mec-corpus",
    "Old English lexicon":   "hall-1894",
    "Wycliffe Bible 1382":   "wycliffe-1382",
    "Vulgate Latin":         "vulgate-latin",
    "PIE reconstruction":    "watkins-pie-2000",
    "Medieval Latin":        "niermeyer-1976",
    "Medieval Church Latin": "niermeyer-1976",
    "Latin grammar":         "de-vaan-2008",
}
