"""
Structural protocols for the two provider seams: LLM and data store.

Any class that has the right methods satisfies these protocols — no explicit
inheritance needed. Mark both @runtime_checkable so isinstance() works.
"""
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class LLMProvider(Protocol):
    """Any object that can turn a prompt string into a generated string."""
    def generate(self, prompt: str) -> str: ...


@runtime_checkable
class EtymologyStore(Protocol):
    """Read-only store for etymology data. Implementors: Neo4jStore, HttpStore."""

    def get_word(self, word: str) -> dict | None: ...
    def get_word_tree(self, word: str) -> dict: ...
    def get_cognates(self, word: str) -> list[dict]: ...
    def get_etymology_claims(self, word: str) -> list[dict]: ...
    def search(self, query: str, limit: int) -> list[dict]: ...

    def get_word_era_meanings(self, word: str) -> list[dict]: ...
    def get_era_timeline(self, word: str) -> list[dict]: ...
    def get_word_in_era(self, word: str, era_name: str) -> dict | None: ...
    def get_era_by_year(self, year: int) -> dict | None: ...
    def get_words_by_era(self, era_name: str, limit: int) -> list[dict]: ...

    def get_word_sources(self, word: str) -> list[dict]: ...
    def get_all_sources(self) -> list[dict]: ...
    def get_source(self, slug: str) -> dict | None: ...
    def get_words_by_source(self, slug: str, limit: int) -> list[dict]: ...
